task: auto

# resume: auto
resume_model_dir: auto
dataset_cfg_path: configs/dataset/humanise_motion.yaml

wrapper_cfg:
  name: MotionDiffuserWrapper
  smplx_model_type: humanise
  pre_methods: ['clip_text']
  normalizer:
    name: NormalizerPoseMotion
    file: out/release/normalize/amass_az_humanise_oc_transl_orient6d_pose6d.pkl
    
metrics: ['recon_trans', 'recon_orient']

loss_weights:
  recon_trans: 1.0
  recon_orient_6d: 1.0

train:
  epoch: 400
  batch_size: 256
  optimizer:
    canonical_bs: 256
  scheduler:
    type: multi_step
    milestones: [50, 100, 150, 250, 300, 350]

net_cfg:
  coord: oc
  repr: traj
  name: DiffuserNetwork
  k_sample: 10
  diffuser:
    name: ObserConditionalDDPM
    timesteps: 200
    pred_type: pred_x0
    obser: false
    obser_type: start_traj
    schedule_cfg:
      beta: [0.0001, 0.01]
      beta_schedule: cosine
      s: 0.008
  model:
    name: TrajFromSceneTextVoxelV0
    d_l: 120
    d_x: 9
    d_betas: 10
    env_sensor:
      name: EnvSensor
      voxel_dim: 8
      radius: 2.0
    target_sensor:
      name: TargetSensor
      voxel_dim: 8