task: auto

dataset_cfg_path: "configs/dataset/amass.yaml"

wrapper_cfg:
  name: MotionDiffuserWrapper
  smplx_model_type: amass
  pre_methods: []
  normalizer:
    name: NormalizerPoseMotion
    file: out/release/normalize/amass_az_humanise_oc_transl_orient6d_pose6d.pkl

eval_ep: 20
metrics: ['recon_trans', 'recon_orient']

loss_weights:
  recon_trans: 1.0
  recon_orient_6d: 1.0

train:
  epoch: 200
  batch_size: 256
  optimizer:
    canonical_bs: 256

net_cfg:
  coord: az
  repr: traj
  name: DiffuserNetwork
  k_sample: 10
  diffuser:
    name: ObserConditionalDDPM
    timesteps: 200
    pred_type: pred_x0
    obser: false
    obser_type: start_traj
    schedule_cfg:
      beta: [0.0001, 0.01]
      beta_schedule: cosine
      s: 0.008
  model:
    name: TrajFromSceneTextVoxelV0
    d_l: 120
    d_x: 9
    d_betas: 10
    env_sensor:
      name: EnvSensor
      voxel_dim: 8
      radius: 2.0
    target_sensor:
      name: TargetSensor
      voxel_dim: 8
